version: '3'

services: 
  db:
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tychy
    volumes: 
      - ./init:/docker-entrypoint-initdb.d
    ports: 
      - 3306:3306
